%TEST_NNDATASETPROCESS_STRUCTURAL

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	dproc = NNDatasetProcess_Structural();
	 
	% get('ELCLASS')
	if isa(NNDatasetProcess_Structural, 'ConcreteElement')
		assert(strcmp(NNDatasetProcess_Structural().get('ELCLASS'), 'NNDatasetProcess_Structural'), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural().get(''ELCLASS'') should return ''NNDatasetProcess_Structural''.')
	end
	 
	% getBuild()
	assert(NNDatasetProcess_Structural.getBuild() == 1 && NNDatasetProcess_Structural.getBuild() > 0, ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.getBuild() should return the NNDatasetProcess_Structural build number.')
	assert(dproc.getBuild() == 1 && dproc.getBuild() > 0 , ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.getBuild() should return the NNDatasetProcess_Structural build number.')
	assert(Element.getBuild(dproc) == 1 && Element.getBuild(dproc) > 0, ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(dproc) should return the NNDatasetProcess_Structural build number.')
	assert(Element.getBuild('NNDatasetProcess_Structural') == 1 && Element.getBuild('NNDatasetProcess_Structural') > 0, ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNDatasetProcess_Structural'') should return the NNDatasetProcess_Structural build number.')
	 
	% getClass()
	assert(strcmp(NNDatasetProcess_Structural.getClass(), 'NNDatasetProcess_Structural'), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.getClass() should return ''NNDatasetProcess_Structural''.')
	assert(strcmp(dproc.getClass(), 'NNDatasetProcess_Structural'), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.getClass() should return ''NNDatasetProcess_Structural''.')
	assert(strcmp(Element.getClass(dproc), 'NNDatasetProcess_Structural'), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(dproc) should return ''NNDatasetProcess_Structural''.')
	assert(strcmp(Element.getClass('NNDatasetProcess_Structural'), 'NNDatasetProcess_Structural'), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNDatasetProcess_Structural'') should return ''NNDatasetProcess_Structural''.')
	 
	% getSubclasses()
	assert(isequal(NNDatasetProcess_Structural.getSubclasses(), subclasses('NNDatasetProcess_Structural', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.getSubclasses() should return the same result as subclasses(''NNDatasetProcess_Structural'', [], [], true).')
	assert(isequal(dproc.getSubclasses(), subclasses('NNDatasetProcess_Structural', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNDatasetProcess_Structural'', [], [], true).')
	assert(isequal(Element.getSubclasses(dproc), subclasses('NNDatasetProcess_Structural', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(dproc) should return the same result as subclasses(''NNDatasetProcess_Structural'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNDatasetProcess_Structural'), subclasses('NNDatasetProcess_Structural', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNDatasetProcess_Structural'') should return the same result as subclasses(''NNDatasetProcess_Structural'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(NNDatasetProcess_Structural.getProps(), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(dproc.getProps(), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(Element.getProps(dproc), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dproc) should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(Element.getProps('NNDatasetProcess_Structural'), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetProcess_Structural'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNDatasetProcess_Structural.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.getProps(category) does not work.')
	tmp = cellfun(@(category) dproc.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(dproc, category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dproc, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNDatasetProcess_Structural', category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_Structural.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_Structural.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetProcess_Structural'', category) does not work.')
	 
	% getPropNumber()
	assert(NNDatasetProcess_Structural.getPropNumber() == length(NNDatasetProcess_Structural.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.getPropNumber() should return the number of properties.')
	assert(dproc.getPropNumber() == length(NNDatasetProcess_Structural.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(dproc) == length(NNDatasetProcess_Structural.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dproc) should return the number of properties.')
	assert(Element.getPropNumber('NNDatasetProcess_Structural') == length(NNDatasetProcess_Structural.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetProcess_Structural'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNDatasetProcess_Structural.getPropNumber(category), categories)) == NNDatasetProcess_Structural.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) dproc.getPropNumber(category), categories)) == NNDatasetProcess_Structural.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(dproc, category), categories)) == NNDatasetProcess_Structural.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dproc, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNDatasetProcess_Structural', category), categories)) == NNDatasetProcess_Structural.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetProcess_Structural'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNDatasetProcess_Structural.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.existsProp(prop) does not work.')
	assert(~dproc.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.existsProp(prop) does not work.')
	assert(~Element.existsProp(dproc, NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(dproc, prop) does not work.')
	assert(~Element.existsProp('NNDatasetProcess_Structural', NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNDatasetProcess_Structural'', prop) does not work.')
	 
	assert_with_error('NNDatasetProcess_Structural.existsProp(NaN)', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsProp(''NNDatasetProcess_Structural'', NaN)', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		assert(NNDatasetProcess_Structural.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.existsProp(prop) does not work.')
		assert(dproc.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.existsProp(prop) does not work.')
		assert(Element.existsProp(dproc, prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(dproc, prop) does not work.')
		assert(Element.existsProp('NNDatasetProcess_Structural', prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNDatasetProcess_Structural'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNDatasetProcess_Structural.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.existsTag(tag) does not work.')
	assert(~dproc.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'dproc.existsTag(tag) does not work.')
	assert(~Element.existsTag(dproc, ''), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(dproc, tag) does not work.')
	assert(~Element.existsTag('NNDatasetProcess_Structural', ''), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNDatasetProcess_Structural'', tag) does not work.')
	 
	assert_with_error('NNDatasetProcess_Structural.existsTag('''')', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsTag(''NNDatasetProcess_Structural'', '''')', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
		assert(NNDatasetProcess_Structural.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.existsTag(tag) does not work.')
		assert(dproc.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.existsTag(tag) does not work.')
		assert(Element.existsTag(dproc, tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(dproc, tga) does not work.')
		assert(Element.existsTag('NNDatasetProcess_Structural', tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNDatasetProcess_Structural'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		assert(NNDatasetProcess_Structural.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropProp(prop) does not work.')
		assert(dproc.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropProp(prop) does not work.')
		assert(Element.getPropProp(dproc, prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dproc, prop) does not work.')
		assert(Element.getPropProp('NNDatasetProcess_Structural', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetProcess_Structural'', prop) does not work.')
	 
		tag = dproc.getPropTag(prop);
		assert(NNDatasetProcess_Structural.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropProp(tag) does not work.')
		assert(dproc.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropProp(tag) does not work.')
		assert(Element.getPropProp(dproc, tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dproc, tag) does not work.')
		assert(Element.getPropProp('NNDatasetProcess_Structural', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetProcess_Structural'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(strcmp(NNDatasetProcess_Structural.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropTag(prop) does not work.')
		assert(strcmp(dproc.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(dproc, prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dproc, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetProcess_Structural', prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetProcess_Structural'', prop) does not work.')
	 
		assert(strcmp(NNDatasetProcess_Structural.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropTag(tag) does not work.')
		assert(strcmp(dproc.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(dproc, tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dproc, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetProcess_Structural', prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetProcess_Structural'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(Category.existsCategory(NNDatasetProcess_Structural.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(dproc.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dproc, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetProcess_Structural'', prop) does not work.')
	 
		assert(Category.existsCategory(NNDatasetProcess_Structural.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(dproc.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dproc, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetProcess_Structural'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(Format.existsFormat(NNDatasetProcess_Structural.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(dproc.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dproc, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetProcess_Structural'', prop) does not work.')
	 
		assert(Format.existsFormat(NNDatasetProcess_Structural.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(dproc.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dproc, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetProcess_Structural'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(ischar(NNDatasetProcess_Structural.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropDescription(prop) does not work.')
		assert(ischar(dproc.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dproc, prop) does not work.')
		assert(ischar(Element.getPropDescription(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetProcess_Structural'', prop) does not work.')
	 
		assert(ischar(NNDatasetProcess_Structural.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.getPropDescription(tag) does not work.')
		assert(ischar(dproc.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dproc, tag) does not work.')
		assert(ischar(Element.getPropDescription(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetProcess_Structural'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		settings = NNDatasetProcess_Structural.getPropSettings(prop);
		settings = dproc.getPropSettings(prop);
		settings = Element.getPropSettings(dproc, prop);
		settings = Element.getPropSettings('NNDatasetProcess_Structural', prop);
	 
		settings = NNDatasetProcess_Structural.getPropSettings(tag);
		settings = dproc.getPropSettings(tag);
		settings = Element.getPropSettings(dproc, tag);
		settings = Element.getPropSettings('NNDatasetProcess_Structural', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		default = NNDatasetProcess_Structural.getPropDefault(prop);
		default = dproc.getPropDefault(prop);
		default = Element.getPropDefault(dproc, prop);
		default = Element.getPropDefault('NNDatasetProcess_Structural', prop);
	 
		default = NNDatasetProcess_Structural.getPropDefault(tag);
		default = dproc.getPropDefault(tag);
		default = Element.getPropDefault(dproc, tag);
		default = Element.getPropDefault('NNDatasetProcess_Structural', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		conditioned_default = NNDatasetProcess_Structural.getPropDefaultConditioned(prop);
		conditioned_default = dproc.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(dproc, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetProcess_Structural', prop);
	 
		conditioned_default = NNDatasetProcess_Structural.getPropDefaultConditioned(tag);
		conditioned_default = dproc.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(dproc, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetProcess_Structural', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(~NNDatasetProcess_Structural.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.checkProp(prop, value) does not work.')
		assert(~dproc.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(dproc, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, prop, value) does not work.')
		assert(~Element.checkProp('NNDatasetProcess_Structural', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_Structural'', prop, value) does not work.')
	 
		assert_with_error('NNDatasetProcess_Structural.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], prop, dproc)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], prop, dproc)
		assert_with_error('Element.checkProp(''NNDatasetProcess_Structural'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNDatasetProcess_Structural.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.checkProp(tag, value) does not work.')
		assert(~dproc.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(dproc, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, tag, value) does not work.')
		assert(~Element.checkProp('NNDatasetProcess_Structural', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_Structural'', tag, value) does not work.')
	 
		assert_with_error('NNDatasetProcess_Structural.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], tag, dproc)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], tag, dproc)
		assert_with_error('Element.checkProp(''NNDatasetProcess_Structural'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNDatasetProcess_Structural.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.checkProp(prop, <conditioned default value>) does not work.')
		assert(dproc.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(dproc, prop, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetProcess_Structural', prop, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_Structural'', prop, <conditioned default value>) does not work.')
	 
		assert(NNDatasetProcess_Structural.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.checkProp(tag, <conditioned default value>) does not work.')
		assert(dproc.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(dproc, tag, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetProcess_Structural', tag, Element.getPropDefaultConditioned(NNDatasetProcess_Structural, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_Structural'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TEMPLATE), ...
		NNDatasetProcess_Structural.ID, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.ID), ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.WAITBAR), ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TRANSFORMATION_RULE), ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NORMALIZATION_RULE), ...
		NNDatasetProcess_Structural.SCALE_FACTOR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.SCALE_FACTOR), ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					dproc.getr(prop) == NNDatasetProcess_Structural.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_Structural.getCategoryName(NNDatasetProcess_Structural.getPropCategory(prop)) ', NNDatasetProcess_Structural.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_Structural.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dproc.getr(TAG) == NNDatasetProcess_Structural.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_Structural.getCategoryName(NNDatasetProcess_Structural.getPropCategory(prop)) ', NNDatasetProcess_Structural.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_Structural.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dproc.getPropSettings(prop))
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop), dproc.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					dproc.getr(prop) == NNDatasetProcess_Structural.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_Structural.getCategoryName(NNDatasetProcess_Structural.getPropCategory(prop)) ', NNDatasetProcess_Structural.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_Structural.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dproc.getr(TAG) == NNDatasetProcess_Structural.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_Structural.getCategoryName(NNDatasetProcess_Structural.getPropCategory(prop)) ', NNDatasetProcess_Structural.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_Structural.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_Structural']);
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dproc.getPropSettings(prop))
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop), dproc.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(dproc.getr(prop), NNDatasetProcess_Structural.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNDatasetProcess_Structural.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetProcess_Structural.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(dproc.getr(TAG), NNDatasetProcess_Structural.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNDatasetProcess_Structural.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetProcess_Structural.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TEMPLATE), ...
		NNDatasetProcess_Structural.ID, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.ID), ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.WAITBAR), ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TRANSFORMATION_RULE), ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NORMALIZATION_RULE), ...
		NNDatasetProcess_Structural.SCALE_FACTOR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.SCALE_FACTOR), ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dproc.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dproc.checkFormat(dproc.getPropFormat(prop), dproc.getr(prop),dproc.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_Structural']);
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_Structural']);
	% 			assert( ...
	% 				~isa(dproc.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess_Structural.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(dproc.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess_Structural.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				dproc.checkFormat(dproc.getPropFormat(prop), dproc.getr(prop),dproc.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess_Structural.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_Structural']);
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dproc.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dproc.checkFormat(dproc.getPropFormat(prop), dproc.getr(prop),dproc.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if dproc.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNDatasetProcess_Structural');
					delete(ancestor(dproc.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNDatasetProcess_Structural.getProps(Category.RESULT))
		for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNDatasetProcess_Structural.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural();
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		assert( ...
			~dproc.isLocked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_Structural.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~dproc.isLocked(TAG), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_Structural.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	dproc.lock()
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural();
	 
	warning_backup = warning('off', 'BRAPH2:NNDatasetProcess_Structural');
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		dproc.lock(prop)
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural();
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		assert( ...
			dproc.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_Structural.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			dproc.isChecked(TAG), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_Structural.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	dproc.unchecked()
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		assert( ...
			~dproc.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_Structural.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	dproc.checked()
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		assert( ...
			dproc.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_Structural.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNDatasetProcess_Structural
	dproc_0 = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TEMPLATE), ...
		NNDatasetProcess_Structural.ID, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.ID), ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.WAITBAR), ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TRANSFORMATION_RULE), ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NORMALIZATION_RULE), ...
		NNDatasetProcess_Structural.SCALE_FACTOR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.SCALE_FACTOR), ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	% NNDatasetProcess_Structural with 1st callbacks
	dproc_1 = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, dproc_0.getCallback(4), ..., ...
		NNDatasetProcess_Structural.ID, dproc_0.getCallback(5), ..., ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, dproc_0.getCallback(10), ..., ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, dproc_0.getCallback(12), ..., ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, dproc_0.getCallback(13), ..., ...
		NNDatasetProcess_Structural.SCALE_FACTOR, dproc_0.getCallback(14), ..., ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess_Structural.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dproc_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dproc_1.get(prop), dproc_0.get(prop)) && ~isa(dproc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dproc_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetProcess_Structural with 2nd callbacks
	dproc_2 = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, dproc_1.getCallback(4), ..., ...
		NNDatasetProcess_Structural.ID, dproc_1.getCallback(5), ..., ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, dproc_1.getCallback(10), ..., ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, dproc_1.getCallback(12), ..., ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, dproc_1.getCallback(13), ..., ...
		NNDatasetProcess_Structural.SCALE_FACTOR, dproc_1.getCallback(14), ..., ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess_Structural.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dproc_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dproc_2.get(prop), dproc_0.get(prop)) && ~isa(dproc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dproc_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetProcess_Structural with 3rd callbacks
	dproc_3 = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, dproc_2.getCallback(4), ..., ...
		NNDatasetProcess_Structural.ID, dproc_2.getCallback(5), ..., ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, dproc_2.getCallback(10), ..., ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, dproc_2.getCallback(12), ..., ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, dproc_2.getCallback(13), ..., ...
		NNDatasetProcess_Structural.SCALE_FACTOR, dproc_2.getCallback(14), ..., ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess_Structural.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dproc_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dproc_3.get(prop), dproc_0.get(prop)) && ~isa(dproc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dproc_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	dproc = NNDatasetProcess_Structural();
	 
	dproc_copy = dproc.copy();
	 
	assert(dproc_copy ~= dproc, ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(dproc_copy, dproc), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		value = dproc.getr(prop);
		value_copy = dproc_copy.getr(prop);
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_Structural.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_Structural.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_Structural.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					dproc_copy.isLocked(prop) == dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_Structural.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dproc_copy.isChecked(prop) == dproc.isChecked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_Structural.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dproc_copy.getPropSeed(prop) == dproc.getPropSeed(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_Structural.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	dproc = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TEMPLATE), ...
		NNDatasetProcess_Structural.ID, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.ID), ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.WAITBAR), ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TRANSFORMATION_RULE), ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NORMALIZATION_RULE), ...
		NNDatasetProcess_Structural.SCALE_FACTOR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.SCALE_FACTOR), ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		if NNDatasetProcess_Structural.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_Structural']);
			% dproc.memorize(prop);
			% warning(warning_backup)
		elseif NNDatasetProcess_Structural.getPropCategory(prop) == Category.EVANESCENT && dproc.getPropFormat(prop) == Format.HANDLE
			dproc.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNDatasetProcess_Structural');
			delete(ancestor(dproc.get(prop), 'figure'))
			warning(warning_backup)
		else
			dproc.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	dproc_copy = dproc.copy();
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		value = dproc.getr(prop);
		value_copy = dproc_copy.getr(prop);
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_Structural.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_Structural.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_Structural.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						dproc_copy.isLocked(prop) == dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.isChecked(prop) == dproc.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.getPropSeed(prop) == dproc.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	dproc_0 = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TEMPLATE), ...
		NNDatasetProcess_Structural.ID, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.ID), ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.WAITBAR), ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TRANSFORMATION_RULE), ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NORMALIZATION_RULE), ...
		NNDatasetProcess_Structural.SCALE_FACTOR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.SCALE_FACTOR), ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	dproc = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, dproc_0.getCallback(4), ..., ...
		NNDatasetProcess_Structural.ID, dproc_0.getCallback(5), ..., ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, dproc_0.getCallback(10), ..., ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, dproc_0.getCallback(12), ..., ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, dproc_0.getCallback(13), ..., ...
		NNDatasetProcess_Structural.SCALE_FACTOR, dproc_0.getCallback(14), ..., ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	dproc_copy = dproc.copy();
	dproc_0_copy = dproc_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
		value = dproc.getr(prop);
		value_copy = dproc_copy.getr(prop);
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_Structural.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_Structural.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_Structural.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == dproc_0.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The callback should be obtained from NNDatasetProcess_Structural.getCallback().' ...
						)
					assert( ...
						value_copy == dproc_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The callback should be obtained from NNDatasetProcess_Structural.getCallback().' ...
						)
				end
	 
					assert( ...
						dproc_copy.isLocked(prop) == dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.isChecked(prop) == dproc.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.getPropSeed(prop) == dproc.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc_template = NNDatasetProcess_Structural();
	dproc = NNDatasetProcess_Structural('TEMPLATE', dproc_template);
	 
	for prop = 1:1:NNDatasetProcess_Structural.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess_Structural.getPropTag(prop));
		switch NNDatasetProcess_Structural.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNDatasetProcess_Structural.TEMPLATE
					assert( ...
						isa(dproc.getr(prop), 'NNDatasetProcess_Structural'), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural TEMPLATE does not work. NNDatasetProcess_Structural.getr(''TEMPLATE'') should be a NNDatasetProcess_Structural element.' ...
						)
					assert( ...
						isa(dproc_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_Structural TEMPLATE does not work. NNDatasetProcess_Structural_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(dproc.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural TEMPLATE does not work. NNDatasetProcess_Structural.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						dproc.getr(prop).get('EL') == dproc_template && dproc.getr(prop).get('PROP') == prop && strcmp(dproc.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural TEMPLATE does not work. NNDatasetProcess_Structural.getr(' TAG ') should be a Callback to dproc_template.' TAG '.'] ...
						)
					assert( ...
						isa(dproc_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_Structural TEMPLATE does not work. NNDatasetProcess_Structural_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural TEMPLATE does not work. NNDatasetProcess_Structural.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(dproc_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_Structural TEMPLATE does not work. NNDatasetProcess_Structural_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TEMPLATE), ...
		NNDatasetProcess_Structural.ID, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.ID), ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.WAITBAR), ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TRANSFORMATION_RULE), ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NORMALIZATION_RULE), ...
		NNDatasetProcess_Structural.SCALE_FACTOR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.SCALE_FACTOR), ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nndatasetprocess_structural_to_be_erased.b2'];
	 
	Element.save(dproc, filename)
	 
	dproc_loaded = Element.load(filename);
	 
	assert( ...
		isequal(dproc.copy(), dproc_loaded), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.save(dproc) and/or NNDatasetProcess_Structural.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural( ...
		NNDatasetProcess_Structural.ELCLASS, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NAME, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.DESCRIPTION, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.TEMPLATE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TEMPLATE), ...
		NNDatasetProcess_Structural.ID, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.ID), ...
		NNDatasetProcess_Structural.LABEL, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.LABEL), ...
		NNDatasetProcess_Structural.NOTES, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NOTES), ...
		NNDatasetProcess_Structural.TOSTRING, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.D, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.WAITBAR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.WAITBAR), ...
		NNDatasetProcess_Structural.GR_LIST, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.GR_LIST), ...
		NNDatasetProcess_Structural.TRANSFORMATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.TRANSFORMATION_RULE), ...
		NNDatasetProcess_Structural.NORMALIZATION_RULE, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.NORMALIZATION_RULE), ...
		NNDatasetProcess_Structural.SCALE_FACTOR, NNDatasetProcess_Structural.getPropDefault(NNDatasetProcess_Structural.SCALE_FACTOR), ...
		NNDatasetProcess_Structural.TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_TRANSFORM_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.INV_NORMALIZE_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.RAW_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.REV_PROCESS_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.EXTRACT_DATA, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.VOI_DICT_LIST, NNDatasetProcess_Structural.getNoValue(), ...
		NNDatasetProcess_Structural.MEMORIZE_DATA, NNDatasetProcess_Structural.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(dproc);
	[dproc_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(dproc_dec ~= dproc, ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_Structural.encodeJSON() or NNDatasetProcess_Structural.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNDatasetProcess_Structural.getPropFormat(prop), num2cell(NNDatasetProcess_Structural.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNDatasetProcess_Structural.getPropFormat(prop), num2cell(NNDatasetProcess_Structural.getProps())) == Format.NET)
		assert(isequal(dproc_dec, dproc), ...
			[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_Structural.encodeJSON() or NNDatasetProcess_Structural.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Construction of an empty structural dataset
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural();
	d = dproc.get('D');
	
	assert(isequal(d.get('DP_DICT').get('LENGTH'), 0), ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not construct an empty dataset correctly.')
end

%% Test 13: None normalisation and inverse normalisation
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural( ...
	    'NORMALIZATION_RULE', 'None');
	
	raw_data = cumsum(randn(5, 100), 2);
	calc_normed_data = dproc.get('NORMALIZE_DATA', raw_data);
	
	assert(isequal(raw_data, calc_normed_data), ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not normalise the data correctly.')
	
	calc_inv_normed_data = dproc.get('INV_NORMALIZE_DATA', calc_normed_data);
	
	assert(isequal(raw_data, calc_inv_normed_data), ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not inverse-normalise the data correctly.')
end

%% Test 14: Scale normalisation and inverse normalisation
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	scale_factor = 10;
	
	dproc = NNDatasetProcess_Structural( ...
	    'NORMALIZATION_RULE', 'Scale', ...
	    'SCALE_FACTOR', scale_factor);
	
	raw_data = cumsum(randn(5, 100), 2);
	known_normed_data = raw_data / scale_factor;
	calc_normed_data = dproc.get('NORMALIZE_DATA', raw_data);
	
	tol = 1e-9;
	
	assert(max(abs(calc_normed_data(:) - known_normed_data(:))) <= tol, ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not normalise the data correctly.')
	
	calc_inv_normed_data = dproc.get('INV_NORMALIZE_DATA', calc_normed_data);
	
	assert(max(abs(calc_inv_normed_data(:) - raw_data(:))) <= tol, ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not inverse-normalise the data correctly.')
end

%% Test 15: None transformation and inverse transformation
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural('TRANSFORMATION_RULE', 'None');
	
	raw_data = cumsum(randn(5, 100), 2);
	calc_transformed = dproc.get('TRANSFORM_DATA', raw_data);
	
	assert(isequal(raw_data, calc_transformed), ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not apply the None transformation correctly.')
	
	calc_inv_transformed = dproc.get('INV_TRANSFORM_DATA', calc_transformed, raw_data(1, :));
	
	assert(isequal(raw_data, calc_inv_transformed), ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not inverse-transform the data correctly.')
end

%% Test 16: First-derivative transformation and inverse transformation
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_Structural('TRANSFORMATION_RULE', 'First derivative');
	
	raw_data = cumsum(randn(5, 100), 2);
	
	known_transformed = raw_data;
	known_transformed(1:end-1, :) = raw_data(2:end, :) - raw_data(1:end-1, :);
	known_transformed(end, :) = 0;
	
	calc_transformed = dproc.get('TRANSFORM_DATA', raw_data);
	
	tol = 1e-9;
	
	assert(max(abs(calc_transformed(:) - known_transformed(:))) <= tol, ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not calculate the first derivative correctly.')
	
	calc_inv_transformed = dproc.get('INV_TRANSFORM_DATA', calc_transformed, raw_data(1, :));
	
	assert(max(abs(calc_inv_transformed(:) - raw_data(:))) <= tol, ...
	    [BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_Structural does not inverse-transform the first derivative correctly.')
end

%% Test 17: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNDatasetProcess_Structural:' BRAPH2.FAIL_TEST], ...
		[' When testing NNDatasetProcess_Structural no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 18: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

