%% EXAMPLE_LIGHTSTRESS
% Script example DIVA pipeline for light stress

clear variables %#ok<*NASGU>

%% Load Spectra Dataset
dproc = NNDatasetProcess_RamanSpectra( ...
    'RAW_DATA_DIR', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'data'], ...
    'TRANSFORMATION_RULE', 'First derivative', ...
    'NORMALIZATION_RULE', 'Scale', ...
    'SCALE_FACTOR', 100, ...
    'STRESS_SEQ', {'WL', 'HL', 'LL', 'SH'}, ...
    'KIND_SEQ', {'AB2', 'CS', 'KL'}, ...
    'LOCATION_SEQ', {'loc1', 'loc2'}, ...
    'TARGETS_TO_REMOVE', {'ps', 'loc2'});

d_sp = dproc.get('D');

% announce memorizing start
fprintf('Memorizing all dataset inputs (may take a few minutes) ...%s', newline);
d_sp.memorize('RAW_DATA');
d_sp.memorize('INPUTS');
fprintf('Finished memorizing all dataset inputs.%s', newline);

fprintf('Memorizing all dataset targets (may take a few minutes) ...%s', newline);
d_sp.memorize('TARGETS');
fprintf('Finished memorizing all dataset targets.%s', newline);

%% Train a Variational Autoencoder
nnvae = NNVariationalAutoencoderMLP('D', d_sp, 'NEURONS_PER_LAYER', [64], 'EPOCHS', 100, 'BATCH', 40);
nnvae.get('TRAIN')

%% Evaluate and Produce Manuscript figures
nne = NNVariationalAutoencoderEvaluator_RS( ...
    'NN', nnvae, ...
    'D', d_sp, ...
    'DPROC', dproc, ...
    'RESOLUTION_CM', 6, ...
    'IDX_LABEL_KIND', 1, ...
    'IDX_LABEL_STRESS', 2, ...
    'IDX_LABEL_LOCATION', 3, ...
    'STRESS_SEQ', {'HL', 'WL', 'LL', 'SH'}, ...
    'STRESS_LABEL', {'High light', 'White light', 'Low light', 'Shade'}, ...
    'STRESS_COLOUR', {'#E64B35FF', '#7E6148FF', '#4DBBD5FF', '#3C5488FF'}, ...
    'STRESS_SHAPE', {'square', 'circle', 'triangle', 'diamond'}, ...
    'DIRECTORY_UTIL_R', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'utilities'], ...
    'DIRECTORY_ANALYSIS', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'analysis'], ...
    'DIRECTORY_FIG', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress']);

nne.memorize('LATENT_REP');
nne.get('PLOT_R_PALETTE');
nne.get('PLOT_R_LS_QNORM_MED');

%% save as b2 file
fprintf('pipeline saving...\n')
tic
mkdir([fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'trained_b2_files']);
Element.save(nne, [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'trained_b2_files' filesep 'nne.b2']);
toc
fprintf('pipeline saved\n')

%% reconstruct the data
saved_b2 = [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'results' filesep 'loc2' filesep 'trained_b2_files' filesep 'nne.b2']
nne = Element.load(saved_b2);

nne = NNVariationalAutoencoderEvaluator_RS( ...
    'NN', nne.get('NN'), ...
    'D', d_sp, ...
    'DPROC', dproc, ...
    'RESOLUTION_CM', 6, ...
    'IDX_LABEL_KIND', 1, ...
    'IDX_LABEL_STRESS', 2, ...
    'IDX_LABEL_LOCATION', 3, ...
    'STRESS_SEQ', {'HL', 'WL', 'LL', 'SH'}, ...
    'STRESS_LABEL', {'High light', 'White light', 'Low light', 'Shade'}, ...
    'STRESS_COLOUR', {'#E64B35FF', '#7E6148FF', '#4DBBD5FF', '#3C5488FF'}, ...
    'STRESS_SHAPE', {'square', 'circle', 'triangle', 'diamond'}, ...
    'DIRECTORY_UTIL_R', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'utilities'], ...
    'DIRECTORY_ANALYSIS', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'analysis'], ...
    'DIRECTORY_FIG', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress']);

detransformation = true;
denormalization = true;
representation_select = 'median';
outdir_prefix = 'crnr_detransformed';
recons_data = nne.get('DATA_RECONSTRUCTION', outdir_prefix, representation_select, denormalization, detransformation);

