%% EXAMPLE_BACTERIALSTRESS_AB
% Script example DIVA pipeline for bacterial stress of Arabidopsis

clear variables %#ok<*NASGU>

%% Load Spectra Dataset
dproc = NNDatasetProcess_RamanSpectra( ...
    'RAW_DATA_DIR', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'data_AB'], ...
    'TRANSFORMATION_RULE', 'First derivative', ...
    'NORMALIZATION_RULE', 'Scale', ...
    'SCALE_FACTOR', 100, ...
    'STRESS_SEQ', {'mock', 'pseudo'}, ...
    'KIND_SEQ', {'AB24hr', 'AB48hr', 'AB72hr'}, ...
    'LOCATION_SEQ', {'loc', 'ps'}, ...
    'TARGETS_TO_REMOVE', {'ps'});

d_sp = dproc.get('D');

% announce memorizing start
fprintf('Memorizing all dataset inputs (may take a few minutes) ...%s', newline);
d_sp.memorize('INPUTS');
fprintf('Finished memorizing all dataset inputs.%s', newline);

fprintf('Memorizing all dataset targets (may take a few minutes) ...%s', newline);
d_sp.memorize('TARGETS');
fprintf('Finished memorizing all dataset targets.%s', newline);

%% Train a Variational Autoencoder
nnvae = NNVariationalAutoencoderMLP('D', d_sp, 'NEURONS_PER_LAYER', [64], 'EPOCHS', 3000, 'BATCH', 40);
nnvae.get('TRAIN')

%% Evaluate and Produce Manuscript figures
nne = NNVariationalAutoencoderEvaluator_RS( ...
    'NN', nnvae, ...
    'D', d_sp, ...
    'DPROC', dproc, ...
    'RESOLUTION_CM', 6, ...
    'IDX_LABEL_KIND', 1, ...
    'IDX_LABEL_STRESS', 2, ...
    'IDX_LABEL_LOCATION', 3, ...
    'STRESS_SEQ', {'mock', 'pseudo'}, ...
    'STRESS_LABEL', {'mock', 'pseudo'}, ...
    'STRESS_COLOUR', {'#4DBBD5FF', '#E64B35FF'}, ...
    'STRESS_SHAPE', {'square', 'circle'}, ...
    'DIRECTORY_UTIL_R', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'utilities'], ...
    'DIRECTORY_ANALYSIS', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'analysis_AB'], ...
    'DIRECTORY_FIG', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress']);

nne.memorize('LATENT_REP');
nne.get('PLOT_R_PALETTE');
nne.get('PLOT_R_LS_QNORM_MED');

%% save as b2 file
fprintf('pipeline saving...\n')
tic
mkdir([fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'trained_b2_files_AB']);
Element.save(nne, [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'trained_b2_files_AB' filesep 'nne.b2']);
toc
fprintf('pipeline saved\n')