%% EXAMPLE_SHADEAVOIDANCESTRESS
% Script example DIVA pipeline for shade avoidance stress

clear variables %#ok<*NASGU>

%% Load Spectra Dataset
dproc = NNDatasetProcess_RamanSpectra( ...
    'RAW_DATA_DIR', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_ShadeAvoidanceStress' filesep 'data'], ...
    'TRANSFORMATION_RULE', 'First derivative', ...
    'NORMALIZATION_RULE', 'Scale', ...
    'SCALE_FACTOR', 100, ...
    'STRESS_SEQ', {'ds', 'ms', 'wl'}, ...
    'KIND_SEQ', {'PhyA', 'PhyB', 'WT'}, ...
    'LOCATION_SEQ', {'leaf', 'petiole'}, ...
    'TARGETS_TO_REMOVE', {'ps'});

d_sp = dproc.get('D');

% announce memorizing start
fprintf('Memorizing all dataset inputs (may take a few minutes) ...%s', newline);
d_sp.memorize('INPUTS');
fprintf('Finished memorizing all dataset inputs.%s', newline);

fprintf('Memorizing all dataset targets (may take a few minutes) ...%s', newline);
d_sp.memorize('TARGETS');
fprintf('Finished memorizing all dataset targets.%s', newline);

%% Train a Variational Autoencoder
nnvae = NNVariationalAutoencoderMLP('D', d_sp, 'NEURONS_PER_LAYER', [64], 'EPOCHS', 3000, 'BATCH', 40);
nnvae.get('TRAIN')

%% Evaluate and Produce Manuscript figures
nne = NNVariationalAutoencoderEvaluator_RS( ...
    'NN', nnvae, ...
    'D', d_sp, ...
    'DPROC', dproc, ...
    'RESOLUTION_CM', 6, ...
    'IDX_LABEL_KIND', 1, ...
    'IDX_LABEL_STRESS', 2, ...
    'IDX_LABEL_LOCATION', 3, ...
    'STRESS_SEQ', {'ds', 'ms', 'wl'}, ...
    'STRESS_LABEL', {'Deep shade', 'Moderate shade', 'White light'}, ...
    'STRESS_COLOUR', {'#E64B35FF', '#4DBBD5FF', '#7E6148FF'}, ...
    'STRESS_SHAPE', {'square', 'circle', 'triangle'}, ...
    'DIRECTORY_UTIL_R', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'utilities'], ...
    'DIRECTORY_ANALYSIS', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_ShadeAvoidanceStress' filesep 'analysis'], ...
    'DIRECTORY_FIG', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_ShadeAvoidanceStress']);

nne.memorize('LATENT_REP');
nne.get('PLOT_R_PALETTE');
nne.get('PLOT_R_LS_QNORM_MED');

%% save as b2 file
fprintf('pipeline saving...\n')
tic
mkdir([fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_ShadeAvoidanceStress' filesep 'trained_b2_files']);
Element.save(nne, [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_ShadeAvoidanceStress' filesep 'trained_b2_files' filesep 'nne.b2']);
toc
fprintf('pipeline saved\n')
