%EXAMPLE_VAEMLP_STRUCTURAL
% Script example pipeline VAEMLP structural data.

clear variables %#ok<*NASGU>

%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectST')) filesep 'Example data ST XLS' filesep 'atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');

%% Load Groups of SubjectST
im_gr1 = ImporterGroupSubjectST_XLS( ...
    'FILE', [fileparts(which('SubjectST')) filesep 'Example data ST XLS' filesep 'ST_Group_1.xlsx'], ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr1 = im_gr1.get('GR');

im_gr2 = ImporterGroupSubjectST_XLS( ...
    'FILE', [fileparts(which('SubjectST')) filesep 'Example data ST XLS' filesep 'ST_Group_2.xlsx'], ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr2 = im_gr2.get('GR');

%% Prepare structural dataset
dproc = NNDatasetProcess_Structural( ...
    'GR_LIST', {gr1, gr2}, ...
    'NORMALIZATION_RULE', 'Scale', ...
    'SCALE_FACTOR', 1 ...
    );

d = dproc.get('D');

%% Train a variational autoencoder
nnvae = NNVariationalAutoencoderMLP( ...
    'D', d, ...
    'EPOCHS', 200, ...
    'BATCH', 32 ...
    );

nnvae.get('TRAIN');

%% Evaluate and visualize latent space
nne = NNVariationalAutoencoderEvaluator( ...
    'NN', nnvae, ...
    'D', d, ...
    'TARGET_NAME', 'group', ...
    'LATENT_DIM_X', 1, ...
    'LATENT_DIM_Y', 2, ...
    'SAVE_DIR', [fileparts(which('example_VAEMLP_STRUCTURAL')) filesep 'VAE evaluation'] ...
    );

nne.get('PLOT_LATENT_REPRESENTATIONS');
